updated kernel removal script

diff --git a/config/includes.chroot_after_packages/usr/local/bin/kernel-remover b/config/includes.chroot_after_packages/usr/local/bin/kernel-remover
--- a/config/includes.chroot_after_packages/usr/local/bin/kernel-remover
+++ b/config/includes.chroot_after_packages/usr/local/bin/kernel-remover
@@ -1,321 +1,200 @@
-#!/bin/sh
-# Modified to work with Lilidog by sleekmason 12-13-20
-# Copyright (C) 2005-2015, Stefan Lippers-Hollmann <s.l-h@gmx.de>
-# Copyright (C) 2007-2010, Joaquim Boura <x-un-i@berlios.de>
-
-# This program is free software; you can redistribute it and/or
-# modify it under the terms of the GNU General Public License
-# as published by the Free Software Foundation; version 2 of the
-# License, or (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-
-# we need gettext (is loaded in ssft.sh or cloned...)
-if [ -f /usr/bin/gettext.sh ]; then
-	. /usr/bin/gettext.sh || exit 1
-else
-	exit 1
-fi
+#!/bin/bash
+# Made for Lilidog by sleekmason 31 Oct 2025
 
 #---------------------------------------------------------------------
-# we need root rights
+# Check for root privileges
 #---------------------------------------------------------------------
 if [ "$(id -u)" -ne 0 ]; then
-	if [ -x "$(command -v su-to-root)" ]; then
-		[ -n "$DISPLAY" ] &&  exec gksudo "${0} $@"
-		exec su-to-root -c "${0} $@"
-	fi
-
-	printf "ERROR: $0 needs root capabilities, please start it as root.\n\n" >&2
-	exit 1
-else
-	if  test  -n "$DISPLAY"  && ! xset q > /dev/null  2>&1 ; then unset DISPLAY; fi
+    printf "ERROR: This script must be run as root.\n" >&2
+    exit 1
 fi
 
+#---------------------------------------------------------------------
+# Variables and defaults
+#---------------------------------------------------------------------
 TEXTDOMAIN="kernel-remover"
 export TEXTDOMAIN
-TEXTDOMAINDIR=/usr/share/locale
+TEXTDOMAINDIR="/usr/share/locale"
 export TEXTDOMAINDIR
 
-#---------------------------------------------------------------------
-usage()
-{
-	echo  "$(basename $0)"
-	echo  "     -G parameter    use parameter as the graphical frontend"
-	echo  "                     one of text | dialog | kdialog | zenity "
-	echo  "     -f              proceed without asking, do complete cleanup"
-	echo  "     -h              show this usage"
-	exit 1
-}
-#---------------------------------------------------------------------
+TITLE="Kernel Remover"
+COOLICON="utilities-system-monitor"
+CURRENTKERNEL=$(uname -r)
+CURRENT=" Cannot remove the active kernel  -  '${CURRENTKERNEL}'"
 
 force=0
+frontend="yad"
 xtra=0
-unset frontend
+
+#---------------------------------------------------------------------
+usage() {
+    echo "$(basename "$0")"
+    echo "     -G parameter    choose frontend (text | yad)"
+    echo "     -f              force cleanup without confirmation"
+    echo "     -h              show this usage"
+    exit 1
+}
+#---------------------------------------------------------------------
+
 while getopts fhxG: name; do
-	case $name in
-	f)
-		force=1
-		;;
-	G)
-		frontend="$OPTARG"
-		;;
-	h)	usage
-		;;
-	x)
-		xtra=1
-		;;
-	*)
-		usage
-		;;
-	esac
+    case $name in
+        f) force=1 ;;
+        G) frontend="$OPTARG" ;;
+        h) usage ;;
+        x) xtra=1 ;;
+        *) usage ;;
+    esac
 done
-shift $(($OPTIND - 1))
+shift $((OPTIND - 1))
 
 #---------------------------------------------------------------------
-prepare()
-{
-	if [ "$force" -eq 0 ]; then
-		# we need ssft 
-		if [ -f /usr/bin/ssft.sh ]; then
-			. /usr/bin/ssft.sh || exit 1
-		else
-			 echo "Please install the package \"ssft\"."
-			 exit 1
-		fi
-	fi
+# Determine frontend (text or yad)
+#---------------------------------------------------------------------
+if [ -z "$frontend" ]; then
+    if [ -n "$DISPLAY" ] && command -v yad >/dev/null 2>&1; then
+        frontend="yad"
+    else
+        frontend="text"
+    fi
+fi
 
-	if [ -n "${frontend}" ]; then
-		case $frontend in
-			text)
-				SSFT_FRONTEND="${frontend}"
-				;;
-			dialog)
-				SSFT_FRONTEND="${frontend}"
-				;;
-			kdialog)
-				SSFT_FRONTEND="${frontend}"
-				;;
-			zenity)
-				SSFT_FRONTEND="${frontend}"
-				;;
-			*)
-				echo unknown frontend
-				exit 1
-				;;
-		esac
-	fi
-
-	if [ -z "$DISPLAY" ] &&  ! /usr/bin/xdpyinfo >/dev/null 2>&1 ; then
-		unset DISPLAY
-	fi
-
-	if [ -z "$DISPLAY" ]; then
-		[ -x /usr/bin/dialog ] && SSFT_FRONTEND=${SSFT_FRONTEND:-"dialog"} || \
-			SSFT_FRONTEND=${SSFT_FRONTEND:-"text"}
-	else
-		if [ -n "$DISPLAY" ] && [ ! -x /usr/bin/zenity ]; then
-			if [ -x /usr/bin/dialog ]; then
-				SSFT_FRONTEND="dialog"
-			else
-				SSFT_FRONTEND="text"
-			fi
-			DISPLAY=""
-		else
-			SSFT_FRONTEND=${SSFT_FRONTEND:-"zenity"}
-		fi
-	fi
-
-	# the current one will not be shown in the list ....
-	CURRENTKERNEL=$(uname -r)
-	TITLE="$(gettext "Removing installed kernels")"
-	PAD="======="
-
-	if [ "${SSFT_FRONTEND}" = "dialog" ] || [ -z "${SSFT_FRONTEND}" ]; then
-		CURRENT="$(eval_gettext "The current (active) kernel is ${PAD}$(uname -r)${PAD}")"
-	else
-		CURRENT="$(eval_gettext "The current (active) kernel is $(uname -r)")"
-	fi
+#---------------------------------------------------------------------
+get_KernelList() {
+    KernelList=""
+    for v in /boot/vmlinuz-*; do
+        Kernel=$(basename "$v" | sed 's/vmlinuz-//')
+        if [ "$Kernel" != "$CURRENTKERNEL" ]; then
+            KernelList="${KernelList} ${Kernel}"
+        fi
+    done
 }
-
 #---------------------------------------------------------------------
-# some useful functions
-#---------------------------------------------------------------------
-inputbox()
-{
-	# inputbox Title Text dummy default
-	Title="$1"
-	Text="$2"
-
-	# $3 not used
-	# The default value if used
-	SSFT_DEFAULT=$4
-
-	ssft_read_string "${Title}" "${Text}";
-}
-
-#---------------------------------------------------------------------
-msgbox()
-{
-	# msgbox title text
-	Title="$1"
-	Text="$2"
-	ssft_display_message "${Title}" "${Text}"
-}
-
-#---------------------------------------------------------------------
-select_more()
-{
-	# select one of a list
-	Title=$1
-	Text=$2
-	shift 2
-
-	if ssft_select_multiple "$Title" "$Text" $@ ; then
-		Selected=$SSFT_RESULT
-		return 0
-	else
-		return 1 
-	fi
-}
-
-#---------------------------------------------------------------------
-yesno()
-{
-	# yesno title text width
-	Title=$1
-	Text=$2
-
-	ssft_yesno "${Title}" "${Text}"
-
-	return $?
-}
-
-#---------------------------------------------------------------------
-remove_one_kernel()
-{
-	Kernel=$1 
-	if [ "${Kernel}" != "${CURRENTKERNEL}" ]; then
-		apt-get remove --purge --yes $(dpkg -l | grep ${Kernel} | awk '{print $2}')
-
-		dpkg -l "linux-headers-${Kernel}-common" >/dev/null 2>&1 && \
-			apt-get remove --purge --yes "linux-headers-${Kernel}-common"
-		dpkg -l "linux-support-${Kernel}" >/dev/null 2>&1 && \
-			apt-get remove --purge --yes "linux-support-${Kernel}"
-
-		# dispose make install artefacts
-		if [ ! -e "/boot/vmlinuz-${Kernel}" ]; then
-			rm -rf /lib/modules/${Kernel}
-		fi
-	fi
-}
-
-#---------------------------------------------------------------------
-
-get_KernelList()
-{
-	for v in /boot/vmlinuz-*; do 
-		Kernel="$(basename $v | sed s/vmlinuz-//)"
-		if [ "${Kernel}" != "${CURRENTKERNEL}" ]; then
-			meta_package="$(echo $(grep-status \
-				-F Depends -s Package \
-				linux-image-${Kernel}) | cut -d: -f 2)"
-
-			case $meta_package in
-				*$Kernel* )
-					# this is an old style kernel
-					KernelList="${KernelList} ${Kernel}"
-
-					continue
-					;;
-			esac
-
-			[ -n "${meta_package}" ] && \
-				meta_status="$(dpkg-query  -f='${STATUS}\n' \
-					-W  ${meta_package}|\
-				 	cut -d ' ' -f 3)" || \
-				meta_status="not-installed"
-
-			if [ "${meta_status}" = "not-installed" ]; then
-				[ -z "${KernelList}" ] && KernelList="${Kernel}" ||\
-				KernelList="${KernelList} ${Kernel}"
-				# echo KernelList="$KernelList"
-			fi
-		fi
-	done
+remove_one_kernel() {
+    Kernel=$1
+    if [ "$Kernel" != "$CURRENTKERNEL" ]; then
+        echo "Removing kernel: $Kernel"
+        apt-get remove --purge --yes $(dpkg -l | grep "$Kernel" | awk '{print $2}') 2>/dev/null
+        dpkg -l "linux-headers-${Kernel}-common" >/dev/null 2>&1 && \
+            apt-get remove --purge --yes "linux-headers-${Kernel}-common"
+        dpkg -l "linux-support-${Kernel}" >/dev/null 2>&1 && \
+            apt-get remove --purge --yes "linux-support-${Kernel}"
+        [ ! -e "/boot/vmlinuz-${Kernel}" ] && rm -rf /lib/modules/"${Kernel}"
+    fi
 }
 
 #---------------------------------------------------------------------
 # Main
 #---------------------------------------------------------------------
-if [ "${xtra}" -eq 1 ]; then
-	KernelList="$@"
-	for i in  ${KernelList} ; do
-		removing="$(eval_gettext "removing kernel ${i}")"
-		echo $removing
-		remove_one_kernel "$i"
-	done
-
-	MSG="$(eval_gettext "the following kernels have been removed: \"${KernelList}\"")"
-	echo $MSG
-
-	exit 0
+if [ "$xtra" -eq 1 ]; then
+    KernelList="$@"
+    for i in ${KernelList}; do
+        echo "Removing kernel $i"
+        remove_one_kernel "$i"
+    done
+    echo "Removed: ${KernelList}"
+    exit 0
 fi
-
-prepare
 
 get_KernelList
 
-if [ -z "${KernelList}" ]; then
-	MSG="$(gettext "There is only one kernel installed on this system. Nothing to be done!")"
-
-	if [ "${force}" -eq 1 ]; then
-		echo "${MSG}"
-	else
-		msgbox "${TITLE}" "${MSG}"
-	fi
-
-	exit 0
+if [ -z "$KernelList" ]; then
+    MSG="There is only one kernel installed on this system. Nothing to be done!"
+    if [ "$frontend" = "text" ]; then
+        echo "$MSG"
+    else
+        yad --center --borders=10 --width=400 --title="$TITLE" \
+            --text="<span foreground='white'>${MSG}</span>" \
+            --button=gtk-ok:0 --gtk-theme="Adwaita:light"
+    fi
+    exit 0
 fi
 
-if [ "${force}" -eq 1 ]; then
-	current="$(eval_gettext "The current (active) kernel is $(uname -r)")"
-	echo ${current}
+if [ "$force" -eq 1 ]; then
+    echo "$CURRENT"
+    for i in ${KernelList}; do
+        echo "Removing kernel $i"
+        remove_one_kernel "$i"
+    done
+    echo "Removed: ${KernelList}"
+    exit 0
+fi
 
-	for i in  ${KernelList} ; do
-		removing="$(eval_gettext "removing kernel ${i}")"
-		echo $removing
-		remove_one_kernel "$i"
-	done
-
-	MSG="$(eval_gettext "the following kernels have been removed: \"${KernelList}\"")"
-	"echo $MSG"
+#---------------------------------------------------------------------
+# User selection (YAD or TEXT)
+#---------------------------------------------------------------------
+if [ "$frontend" = "text" ]; then
+    echo "$CURRENT"
+    echo "Available kernels to remove:"
+    echo "$KernelList"
+    echo
+    read -rp "Enter kernel(s) to remove (space-separated): " CHOICE
 else
-	select_more "${TITLE}" "${CURRENT}" ${KernelList} 
-	if [ "$?" -ne 0 ]; then
-		exit 10
-	fi
+    # Prepare list for yad
+    yad_list=()
+    for k in ${KernelList}; do
+        yad_list+=(FALSE "$k")
+    done
 
-	if [ -z "${SSFT_RESULT}" ]; then
-		exit 12
-	fi
+    CHOICE=$(yad --list --checklist \
+        --title="$TITLE" \
+        --window-icon="$COOLICON" \
+        --width=460 --height=222 \
+        --center --borders=10 \
+        --column="Select" --column="Kernel(s)" \
+        --text="<span foreground='white'>${CURRENT}</span>" \
+        --separator=" " \
+        "${yad_list[@]}" \
+        2>/dev/null)
 
-	one_removed=false
-	for i in ${SSFT_RESULT}; do
-		MSG="$i : $(gettext "Should I remove this kernel?") "
-		yesno "${TITLE}" "${MSG}"
+    # Remove any 'TRUE' text from selection
+    CHOICE=$(echo "$CHOICE" | sed 's/\bTRUE\b//g')
+fi
 
-		if [ "$?" -eq 0 ]; then
-			remove_one_kernel "$i"
-			one_removed=true
-		else
-			msgbox "${TITLE}" "$(gettext "Kernel not removed:") $i"
-		fi
-	done
+[ -z "$CHOICE" ] && exit 0
+
+#---------------------------------------------------------------------
+# Confirmation dialog before removal
+#---------------------------------------------------------------------
+if [ "$frontend" = "text" ]; then
+    echo
+    echo "The following kernel(s) have been selected for removal: ${CHOICE}"
+    read -rp "Would you like to continue? [y/N]: " CONFIRM
+    case "$CONFIRM" in
+        [yY][eE][sS]|[yY]) ;;
+        *) echo "Operation canceled."; exit 0 ;;
+    esac
+else
+    # Format selection as bullet list
+    BULLETS=""
+    for k in ${CHOICE}; do
+        BULLETS="${BULLETS}• ${k}\n"
+    done
+
+    yad --question \
+        --title="$TITLE" \
+        --window-icon="$COOLICON" \
+        --width=460 --center --borders=10 \
+        --text="<span foreground='white'>The following kernel(s) have been selected for removal:\n<b>${BULLETS}</b>\n\nWould you like to continue?</span>" \
+        --button=gtk-yes:0 --button=gtk-no:1
+    [ $? -ne 0 ] && exit 0
+fi
+
+#---------------------------------------------------------------------
+# Proceed with confirmed removal
+#---------------------------------------------------------------------
+for i in ${CHOICE}; do
+    echo "Confirmed removal for $i"
+    remove_one_kernel "$i"
+done
+
+if [ "$frontend" = "yad" ]; then
+    yad --info \
+        --title="$TITLE" \
+        --window-icon="$COOLICON" \
+        --width=460 --center --borders=10 \
+        --text="<span foreground='white'>Removed kernel(s):<b> ${CHOICE}</b></span>" \
+else
+    echo "Removed kernel(s): ${CHOICE}"
 fi
 
 exit 0
-
